# MIT License
# Copyright (c) 2023 Mitchell Hashimoto
# Copyright (c) 2026 Crrow

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - skip: true

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Other
      order: 999
  filters:
    exclude:
      - "^chore:"
      - "^ci:"
      - "^style:"
      - Merge pull request
      - Merge branch

release:
  prerelease: auto
  header: |
    ## libxev-go {{ .Tag }}

    Go bindings for [libxev](https://github.com/Hejsil/libxev), a high-performance event loop library.

    ### Installation

    ```bash
    go get github.com/crrow/libxev-go@{{ .Tag }}
    ```

    ### Requirements

    - Go 1.24+
    - [Zig](https://ziglang.org/) 0.14+ (for building libxev)
    - libffi (usually pre-installed on most systems)

  footer: |
    ---

    **Full Changelog**: https://github.com/crrow/libxev-go/compare/{{ .PreviousTag }}...{{ .Tag }}
